# 1)

1.1)



1.2)



# 2)

### 2.1)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import math
%config InlineBackend.figure_format = 'retina'
%matplotlib inline
from sklearn.utils import shuffle
import scipy.io as sio
plt.rcParams['figure.figsize'] = 8,8

In [20]:
X_and_Y = np.load('arrhythmia.npy')
np.random.shuffle(X_and_Y)
X = X_and_Y[:, :279]    # First column to second last column: Features (numerical values) 
Y = X_and_Y[:, 279]   # Last column: Labels (0 or 1)
#print(X.shape, Y.shape)
#print("full")
#print(X_and_Y)
print("X")
print(X)

X
[[ 2.70e+01  1.00e+00  1.60e+02 ...  1.90e+00  1.10e+01  2.50e+01]
 [ 3.60e+01  1.00e+00  1.53e+02 ...  1.70e+00  1.97e+01  3.43e+01]
 [ 2.90e+01  0.00e+00  1.72e+02 ...  1.70e+00  2.04e+01  3.06e+01]
 ...
 [ 3.30e+01  1.00e+00  1.50e+02 ...  2.10e+00  2.13e+01  4.18e+01]
 [ 5.00e+01  0.00e+00  1.68e+02 ...  8.00e-01 -5.90e+00  1.00e-01]
 [ 6.90e+01  1.00e+00  1.60e+02 ...  1.30e+00  1.18e+01  2.35e+01]]


In [87]:
threshold = round(len(Y) * 0.8)

X_train_val = X[:threshold, :] # Get features from train + val set.
X_test      = X[threshold+1:, :] # Get features from test set.     
Y_train_val = Y[:threshold] # Get labels from train + val set.
Y_test      = Y[threshold+1:] # Get labels from test set.

print(X)

[[ 2.70e+01  1.00e+00  1.60e+02 ...  1.90e+00  1.10e+01  2.50e+01]
 [ 3.60e+01  1.00e+00  1.53e+02 ...  1.70e+00  1.97e+01  3.43e+01]
 [ 2.90e+01  0.00e+00  1.72e+02 ...  1.70e+00  2.04e+01  3.06e+01]
 ...
 [ 3.30e+01  1.00e+00  1.50e+02 ...  2.10e+00  2.13e+01  4.18e+01]
 [ 5.00e+01  0.00e+00  1.68e+02 ...  8.00e-01 -5.90e+00  1.00e-01]
 [ 6.90e+01  1.00e+00  1.60e+02 ...  1.30e+00  1.18e+01  2.35e+01]]


In [88]:
X_folds = np.array_split(X, 3, 0)
print(X_folds[1].shape)

(151, 279)


In [92]:
X_folds_copy = X_folds.copy()
print(X_folds_copy[2].shape)
X_list = X_folds_copy.pop(1)
print(X_list.shape)
print(X_folds_copy[1].shape)

(150, 279)
(151, 279)
(150, 279)


In [93]:
X2 = np.concatenate(X_folds_copy)

In [94]:
print(X2)

[[ 2.70e+01  1.00e+00  1.60e+02 ...  1.90e+00  1.10e+01  2.50e+01]
 [ 3.60e+01  1.00e+00  1.53e+02 ...  1.70e+00  1.97e+01  3.43e+01]
 [ 2.90e+01  0.00e+00  1.72e+02 ...  1.70e+00  2.04e+01  3.06e+01]
 ...
 [ 3.30e+01  1.00e+00  1.50e+02 ...  2.10e+00  2.13e+01  4.18e+01]
 [ 5.00e+01  0.00e+00  1.68e+02 ...  8.00e-01 -5.90e+00  1.00e-01]
 [ 6.90e+01  1.00e+00  1.60e+02 ...  1.30e+00  1.18e+01  2.35e+01]]
